[General]
# Palette — Gruvbox Dark (matching MangoWM)
textColor=#ebdbb2
errorColor=#fb4934
backgroundColor=#282828
panelColor=#282828
activeColor=#fabd2f

# Background
backgroundImage=/home/null/Downloads/wallpaper.jpg
backgroundFillMode=aspectCrop
backgroundOpacity=100
backgroundGlassEnabled=true
backgroundGlassIntensity=60
backgroundTintColor=#282828
backgroundTintIntensity=30

# Typography
fontFamily=JetBrainsMono Nerd Font
baseFontSize=14
sessionsFontSize=15

# Controls
controlCornerRadius=0
controlOpacity=12
controlBlurEnabled=false
controlBlurIntensity=0
controlAccentColor=#3c3836
controlFillBaseColor=#32302f
controlFillHoverColor=#3c3836
controlFillFocusColor=#504945
controlFillPressedColor=#282828
allowEmptyPassword=false
showUserSelector=false
showSessionSelector=true
useIpaMask=false
simpleMaskChar=*
randomizePasswordMask=false
autoFocusPassword=true
animationDuration=120
passwordFlashLoops=2
passwordFlashOnDuration=120
passwordFlashOffDuration=120
